### ISSUE TITLE
New node is not added to cluster 

### ISSUE THREAD

**Issue by mpas** [pellepelster/hivemq-consul-cluster-discovery#1]
When testing the plugin using docker the following scenario results in a invalid cluster.

[docker-compose up]
- starts up consul 
- starts up hivemq node-1
- starts up hivemq node-2
Result: OK [cluster of 2 nodes]!

**Next steps:**
[docker-compose stop node-2]
- stops hivemq node-2

[docker rm node-2 container]
- removes docker container for hivemq node-2

[docker-compose up node-2]
- creates a new hivemq node-2 container and starts this one

Result: NOK [2 clusters with 1 node each]

They never join into 1 cluster anymore.

**Comment by mpas** [comment]
Cause of the problem is that services are lookup by name and the service id should be taken into account. Added a pull request which adds a random service id.

**Comment by pellepelster** [comment]
thanks for your PR
